title: Mika's website
# email:
description: >-
  Physics, IT, information security, open source etc.
# baseurl:
url: "https://agx.fi"
# markdown: kramdown
twitter_username: AgenttiX
github_username: AgenttiX
google_analytics: G-QNHX8YQ2VP

# https://www.embeddedlog.com/jekyll-theme-rtd/configuration/configyml.html
# theme: jekyll-theme-slate
remote_theme: carlosperate/jekyll-theme-rtd
search_enabled: true

plugins:
  - jekyll-feed

exclude:
  - README.md
